version: '3'

services:
  api:
    container_name: api
    restart: always
    build: ./api  #location of Dockerfile
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b :8000 app:app

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "8001:8001"
    depends_on:
      - api